# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitify < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cocoide/commitify/releases/download/v0.3.0/commitify_Darwin_x86_64.tar.gz"
      sha256 "3d610f6ac586f622cb58bcaf2f634cfcc6b316f24f739b93bb44c7737f888362"

      def install
        bin.install "commitify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cocoide/commitify/releases/download/v0.3.0/commitify_Darwin_arm64.tar.gz"
      sha256 "d242ba43f3120da00e256fea9fd2dcf3630c27b6d71408587a779639bd073b2a"

      def install
        bin.install "commitify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cocoide/commitify/releases/download/v0.3.0/commitify_Linux_arm64.tar.gz"
      sha256 "5bee90410d80ac8f99d618d47706a5d68e01df322da8f9a8d6a6b09fbe86d93c"

      def install
        bin.install "commitify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cocoide/commitify/releases/download/v0.3.0/commitify_Linux_x86_64.tar.gz"
      sha256 "c6db46ae05270008e6a7f864fecaeb202a28211b677eeafb97002d0af8aba3e9"

      def install
        bin.install "commitify"
      end
    end
  end
end
