# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitify < Formula
  desc ""
  homepage ""
  version "0.4.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cocoide/commitify/releases/download/v0.4.5/commitify_Darwin_x86_64.tar.gz"
      sha256 "6ff5dfe744cbf532cffa138469096068b01187dfe4652160605922d93558d2c4"

      def install
        bin.install "commitify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cocoide/commitify/releases/download/v0.4.5/commitify_Darwin_arm64.tar.gz"
      sha256 "df8c8e41569249fd58690a7e85482b9ea8ac5cab55a3dc50af216ad67629c382"

      def install
        bin.install "commitify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cocoide/commitify/releases/download/v0.4.5/commitify_Linux_arm64.tar.gz"
      sha256 "2395d7260de6824de23b83f5ce94a633557e931eaae1fd1af60caf04c99b2c4e"

      def install
        bin.install "commitify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cocoide/commitify/releases/download/v0.4.5/commitify_Linux_x86_64.tar.gz"
      sha256 "c7e7b5434b4967875b1dbf3c960cae1d7b2e7927b12ff9b877a49196a0b0b829"

      def install
        bin.install "commitify"
      end
    end
  end
end
